// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ejvZrFTDobDX2Eeu0RMT9xDgzoHwKY4',
    appId: '1:235765491708:web:755f2f789a97f8436e3479',
    messagingSenderId: '235765491708',
    projectId: 'chat-app-5fa8a',
    authDomain: 'chat-app-5fa8a.firebaseapp.com',
    storageBucket: 'chat-app-5fa8a.firebasestorage.app',
    measurementId: 'G-WD1JWKMFGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKncFS7KNhWsVq_HVXW4D8lTHEVH9f_mU',
    appId: '1:235765491708:android:3b51e4f06ae0ee356e3479',
    messagingSenderId: '235765491708',
    projectId: 'chat-app-5fa8a',
    storageBucket: 'chat-app-5fa8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjD35cT5C_OPhDnNSKzysheQw2pfeni1A',
    appId: '1:235765491708:ios:89b47b8e57a4c5076e3479',
    messagingSenderId: '235765491708',
    projectId: 'chat-app-5fa8a',
    storageBucket: 'chat-app-5fa8a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjD35cT5C_OPhDnNSKzysheQw2pfeni1A',
    appId: '1:235765491708:ios:89b47b8e57a4c5076e3479',
    messagingSenderId: '235765491708',
    projectId: 'chat-app-5fa8a',
    storageBucket: 'chat-app-5fa8a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ejvZrFTDobDX2Eeu0RMT9xDgzoHwKY4',
    appId: '1:235765491708:web:4268bed1ead834d06e3479',
    messagingSenderId: '235765491708',
    projectId: 'chat-app-5fa8a',
    authDomain: 'chat-app-5fa8a.firebaseapp.com',
    storageBucket: 'chat-app-5fa8a.firebasestorage.app',
    measurementId: 'G-6L2S3G0WHF',
  );
}
